### ISSUE TITLE
[ENH] Plan과 Reply의 연관관계

### ISSUE THREAD

**Issue by mangdo** [ActionPlan23/ActionPlanBack#5]
현재는 Plan과 Reply사이에서 **연관 관계**가 전혀 없습니다.
Reply는 planId값을 직접 다루고 있습니다.

``` java
public class Reply extends Timestamped {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long replyId;

    @Column(nullable = false)
    private String replyContent;

    @Column(nullable = false)
    private String replyPassword;


    @Column(nullable = false)
    private String replyWriter;

    @Column(nullable = false)
    private Long planId; // <- ???

    public Reply(ReplyRequestDto requestDto, Long planId){
        this.replyContent = requestDto.getReplyContent();
        this.replyWriter = requestDto.getReplyWriter();
        this.replyPassword = requestDto.getReplyPassword();
        this.planId = planId;
    }
}
```

Reply와 Plan사이의 연관 관계를 설정해야 할 것 같습니다.
-> 단방향 OneToMany / 단방향 ManyToOne / 양방향 ManyToOne

**Comment by cwangg897** [comment]
<pre>
<code>
public class Reply extends Timestamped {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long replyId;

    @Column(nullable = false)
    private String replyContent;

    @Column(nullable = false)
    private String replyPassword;


    @Column(nullable = false)
    private String replyWriter;


    @ManyToOne
    @JoinColumn(name = "PLAN_ID")
    private Plan plan;
    
    public Reply(ReplyRequestDto requestDto, Plan plan){
        this.replyContent = requestDto.getReplyContent();
        this.replyWriter = requestDto.getReplyWriter();
        this.replyPassword = requestDto.getReplyPassword();
        this.plan = plan;
    }
</pre>
</code>
단방향매핑 


<pre>
<code>
// 상세페이지 조회
    @Transactional
    public DetailOneDto getPlan(Long id) {
        Plan plan = planRepository.findById(id).orElseThrow(
                ()-> new IllegalArgumentException("상세페이지 조회시: 존재하지않는 게시글 아이디입니다.")
        );
        List<Reply> list = replyRepository.findAllByPlanPlanId(id);
        DetailOneDto detailOneDto = new DetailOneDto(plan, list);
        return detailOneDto;
    }

</pre>
</code>
PlanService 이렇게변경함


<pre>
<code>
public class DetailOneDto {

    private Plan plan;
    private List<Reply> replyList;
}
</pre>
</code>
상세페이지볼떄 이 dto를 반환

![image](https://user-images.githubusercontent.com/79621675/125187593-5461b680-e26b-11eb-8045-68bc090455da.png)
![image](https://user-images.githubusercontent.com/79621675/125187601-5b88c480-e26b-11eb-813e-f1c5a6c421ff.png)
ARC결과

**Comment by mangdo** [comment]
양방향 연관 관계로 하니 plan을 조회할 때 reply를 join을 사용하여 하나의 쿼리로 가져오지만,
간단히 plan이 존재하는지 유무를 체크할 때까지도 reply를 같이 조회하며 성능 이슈가 발생 하였습니다.

+) 2021-07-14 추가
가급적 지연 로딩(FetchType.LAZY)만 사용해야 합니다!!! 
특히 실무에서와 같이 테이블이 복잡하게 얽혀있는 경우에는 지연 로딩을 사용해야 합니다. 
그 이유는 다음과 같습니다.

1. 즉시 로딩을 사용하면 예상하지 못한 SQL이 발생한다.
    : 이 부분이 현재 저희 프로젝트에서 생긴 이슈였으며 이 이유로 FetchType.EAGER -> FetchType.LAZY로 변경하였습니다.
2. 즉시 로딩은 JPQL에서 N+1 문제를 일으킨다.


```sql
select
        plan0_.plan_id as plan_id1_0_0_,
        plan0_.created_at as created_2_0_0_,
        plan0_.modified_at as modified3_0_0_,
        plan0_.content as content4_0_0_,
        plan0_.plan_password as plan_pas5_0_0_,
        plan0_.plan_writer as plan_wri6_0_0_,
        plan0_.success as success7_0_0_,
        plan0_.title as title8_0_0_,
        replylist1_.plan_id as plan_id7_1_1_,
        replylist1_.reply_id as reply_id1_1_1_,
        replylist1_.reply_id as reply_id1_1_2_,
        replylist1_.created_at as created_2_1_2_,
        replylist1_.modified_at as modified3_1_2_,
        replylist1_.plan_id as plan_id7_1_2_,
        replylist1_.reply_content as reply_co4_1_2_,
        replylist1_.reply_password as reply_pa5_1_2_,
        replylist1_.reply_writer as reply_wr6_1_2_ 
    from
        plan plan0_ 
    left outer join
        reply replylist1_ 
            on plan0_.plan_id=replylist1_.plan_id 
    where
        plan0_.plan_id=?


insert 
    into
        reply
        (created_at, modified_at, plan_id, reply_content, reply_password, reply_writer, reply_id) 
    values
        (?, ?, ?, ?, ?, ?, ?)

```
